var R=[
  {n:"50 Kalo",a:"Piazza Sannazaro 201b, Chiaia",pl:2,pr:"€€ · ~22€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.google.com/search?q=50+Kalo+pizzeria+Napoli",st:"Pizzeria di Ciro Salvo a Mergellina. Una delle 50 migliori pizzerie del mondo secondo le classifiche internazionali. Impasto perfetto, ingredienti selezionati, cornicione da manuale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["50 Kalo e nella lista delle 50 migliori pizzerie del mondo: Ciro Salvo e un maestro.","L impasto e il punto di forza: lievitazione lunga, cornicione fragrante e alveolato.","A Mergellina con vista sul Golfo: la pizza napoletana nella location piu bella."]},
  {n:"A Figlia ro Marenaro",a:"Via Alfonso d'Aragona 10, Centro Storico",pl:2,pr:"€€ · ~35€",cu:"Napoletana di Mare",tg:"pesce",ws:"https://www.google.com/search?q=A+Figlia+ro+Marenaro+ristorante",st:"Trattoria di pesce nel cuore del centro storico. Cucina marinara napoletana autentica: zuppa di pesce, frittura di paranza, spaghetti alle vongole. Gestione familiare da generazioni.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["La zuppa di pesce napoletana qui e quella della tradizione marinara partenopea: ricca e profumata.","Gestione familiare da generazioni: la qualita del pesce non scende mai.","Un indirizzo che i napoletani tengono gelosamente per se."]},
  {n:"A Finestrella a Marechiaro",a:"Via Marechiaro 23, Posillipo",pl:3,pr:"€€€ · ~60€",cu:"Pesce Napoletano",tg:"pesce",ws:"https://www.google.com/search?q=A+Finestrella+a+Marechiaro+Napoli",st:"Il ristorante della celebre canzone napoletana. A Marechiaro, Posillipo, con terrazza direttamente sul mare. Cucina di pesce della tradizione: frittura, pasta al mare, crudi del Golfo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["La finestrella della canzone di Tosti e qui: un ristorante che e anche un pezzo di storia.","La terrazza sul mare di Posillipo con il Golfo e il Vesuvio come sfondo: unica.","La pasta con le vongole veraci e gli spaghetti ai frutti di mare: mare nel piatto."]},
    {n:"Aria",a:"Via Giordano Bruno 43, Chiaia",pl:5,pr:"€€€€€ · ~120€",cu:"Alta Cucina Italiana",tg:"italiana",ws:"https://www.google.com/search?q=Aria%20ristorante",st:"Una stella Michelin a Chiaia. Chef Diego Nuzzo. Cucina italiana contemporanea con forte radici campane. Ambiente elegante nel quartiere piu chic di Napoli.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Chef Nuzzo costruisce piatti di grande equilibrio tra tradizione campana e creativita.","Chiaia e il quartiere piu elegante di Napoli: Aria ne e il ristorante di riferimento.","Una stella Michelin per una cucina che non smette di sorprendere."]},
  {n:"Calasole",a:"Via Posillipo 91, Posillipo",pl:3,pr:"€€€ · ~60€",cu:"Pesce Napoletano",tg:"pesce",ws:"https://www.google.com/search?q=Calasole+ristorante+Posillipo+Napoli",st:"Ristorante di pesce a Posillipo con terrazza panoramica sul Golfo di Napoli. Cucina napoletana di mare: crudi, frittura, pasta al mare. Tramonto sul Golfo con il Vesuvio.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La terrazza di Posillipo con il tramonto sul Golfo e il Vesuvio: indimenticabile.","I crudi del Golfo di Napoli con il pane cafone tostato: l antipasto piu napoletano.","Posillipo e il colle del dolce far niente: Calasole ne e l indirizzo gastronomico."]},
  {n:"Cantina di Via Sapienza",a:"Via della Sapienza 40, Centro Storico",pl:1,pr:"€ · ~20€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Cantina%20di%20Via%20Sapienza%20ristorante",st:"Osteria napoletana autentica nel cuore del centro storico UNESCO. Cucina popolare: pasta e fagioli, frittata di pasta, trippa napoletana. Vino sfuso della casa.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La cucina napoletana povera qui e quella vera: pasta e fagioli densa e profumata.","Vino sfuso e conti bassissimi: il miracolo del cibo buono a prezzi impossibili.","Nel centro storico UNESCO: l autenticita che i turisti non trovano mai."]},
  {n:"Coco Loco",a:"Via Bisignano 30, Chiaia",pl:2,pr:"€€ · ~36€",cu:"Napoletana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Coco+Loco+Napoli+Chiaia",st:"Ristorante contemporaneo a Chiaia. Cucina napoletana rivisitata in chiave moderna: polpette gourmet, pasta e patate con la provola, spaghetti alle vongole. Ambiente informale e vivace.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["La cucina napoletana contemporanea a Chiaia: classici rivisitati con ingredienti di qualita.","Le polpette di Coco Loco sono il piatto simbolo: carne di qualita e sugo napoletano.","Ambiente vivace e informale: il posto giusto per una cena senza pretese ma di qualita."]},
  {n:"Concettina ai Tre Santi",a:"Via Arena della Sanita 7, Sanita",pl:2,pr:"€€ · ~20€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.google.com/search?q=Concettina+ai+Tre+Santi+Napoli",st:"Pizzeria storica dal 1951 nel Rione Sanita. Chef Ciro Oliva. Pizza napoletana contemporanea con ingredienti di eccellenza: mozzarella di bufala, pomodoro San Marzano, friarielli.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Dal 1951 nel Rione Sanita: la pizzeria storica che ha reinventato la pizza gourmet.","Ciro Oliva porta ingredienti di eccellenza sulla pizza napoletana senza tradirne l anima.","Il Rione Sanita e il quartiere piu autentico di Napoli: la pizzeria ne e il simbolo."]},
  {n:"Consorzio Napoli",a:"Via Benedetto Croce 37, Spaccanapoli",pl:2,pr:"€€ · ~38€",cu:"Napoletana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Consorzio%20Napoli%20ristorante",st:"Bistrot contemporaneo nel cuore di Spaccanapoli. Cucina napoletana rivisitata con ingredienti bio, vini naturali e atmosfera informale. Frequentato dai napoletani come indirizzo di qualita.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["La cucina napoletana di nuova generazione trova qui un indirizzo credibile e di qualita.","Vini naturali e ingredienti bio: una scelta etica che non sacrifica il gusto.","Spaccanapoli autentico: un bistrot contemporaneo dove si sentono parlare napoletano."]},
  {n:"Da Cicciotto",a:"Calata Ponticello a Marechiaro 32, Posillipo",pl:3,pr:"€€€ · ~65€",cu:"Pesce Napoletano",tg:"pesce",ws:"https://www.google.com/search?q=Da+Cicciotto+Marechiaro+Napoli",st:"Ristorante di pesce storico a Marechiaro, Posillipo. Direttamente sul mare con accesso al pontile. Cucina di pesce napoletana: frittura, crudi, spaghetti alle vongole. Vista sul Golfo.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Marechiaro e il posto piu romantico di Napoli: la canzone di Tosti e nata qui.","Il pontile sul mare e la frittura di paranza: l esperienza napoletana piu iconica.","Da Cicciotto e una delle ultime trattorie di pesce autentiche affacciate sul Golfo."]},
  {n:"Da Diego",a:"Via Martucci 43, Chiaia",pl:1,pr:"€ · ~20€",cu:"Street Food Napoletano",tg:"italiana",ws:"https://www.google.com/search?q=Da+Diego+Napoli+Chiaia",st:"Friggitoria e rosticceria storica a Chiaia. Street food napoletano autentico: cuoppo di frittura, crocche di patate, pizzette fritte, zeppole. Il fast food partenopeo nella sua forma migliore.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il cuoppo di frittura di Da Diego e uno dei migliori di Napoli: leggero e croccante.","Le crocche di patate con il pepe sono la merenda napoletana per eccellenza.","Fila perenne ma vale ogni minuto: street food autentico a prezzi da centesimi."]},
  {n:"Da Mimi alla Ferrovia",a:"Via Alfonso d'Aragona 19, Centro Storico",pl:2,pr:"€€ · ~40€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Da+Mimi+alla+Ferrovia+Napoli",st:"Ristorante storico napoletano vicino alla Stazione Centrale. Cucina partenopea della tradizione: sartù di riso, pasta e patate, genovese. Frequentato da personaggi illustri dal 1945.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Dal 1945 vicino alla Stazione: la cucina napoletana dei viaggiatori e degli artisti.","Il sartu di riso e il piatto piu laborioso della cucina napoletana: qui e quello storico.","Eduardo De Filippo, Totò e Pino Daniele ci hanno mangiato: la storia nel piatto."]},
  {n:"Gelateria Mennella",a:"Via Giacinto Gigante 37, Chiaia",pl:1,pr:"€ · ~5€",cu:"Gelateria",tg:"italiana",ws:"https://www.google.com/search?q=Gelateria%20Mennella%20ristorante",st:"La miglior gelateria di Napoli a Chiaia. Gusti artigianali con ingredienti di eccellenza: pistacchio di Bronte, nocciola piemontese, limone di Sorrento. Gelato tradizionale napoletano.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Il gelato artigianale piu buono di Napoli: pistacchio di Bronte e nocciola piemontese.","Il limone di Sorrento in sorbetto e una delle cose piu buone che si possano mangiare a Napoli.","Una sosta obbligatoria dopo la cena o in qualsiasi momento della giornata."]},
  {n:"Il Comandante",a:"Via Partenope 45, Lungomare",pl:5,pr:"€€€€€ · ~150€",cu:"Alta Cucina Campana",tg:"italiana",ws:"https://www.google.com/search?q=Il%20Comandante%20ristorante",st:"Due stelle Michelin al Romeo Hotel sul Lungomare. Chef Salvatore Bianco. Cucina campana d autore con vista sul Castel dell Ovo e il Golfo di Napoli. Una delle terrazze piu belle d Italia.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Due stelle Michelin con vista sul Golfo di Napoli: difficile fare di meglio.","Salvatore Bianco porta la cucina campana a livelli di assoluta eccellenza.","Il Golfo di Napoli dal ristorante al tramonto: uno spettacolo che accompagna i piatti."]},
  {n:"Il Ristorante Alain Ducasse Napoli",a:"Via Partenope 12, Lungomare",pl:5,pr:"€€€€€ · ~200€",cu:"Alta Cucina Francese",tg:"internazionale",ws:"https://www.google.com/search?q=Il%20Ristorante%20Alain%20Ducasse%20Napoli%20ristorante",st:"Nuova stella Michelin 2026 all Hotel Excelsior sul Lungomare. Alain Ducasse porta il suo standard mondiale nel Golfo di Napoli. Vista sul Vesuvio e Castel dell Ovo.",mi:{s:1,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:15,l:"15/20"},rv:["Alain Ducasse sbarca a Napoli con la prima stella 2026: attesa ripagata.","La vista sul Vesuvio dal Lungomare e il contesto piu iconico possibile.","L impronta Ducasse e riconoscibile: tecnica francese con ingredienti campani d eccellenza."]},
  {n:"L'Ebrezza di Noè",a:"Vico Belledonne a Chiaia 14, Chiaia",pl:2,pr:"€€ · ~35€",cu:"Enoteca di Campagna",tg:"italiana",ws:"https://www.google.com/search?q=L+Ebrezza+di+Noe+Napoli",st:"Enoteca con cucina a Chiaia. Selezione di vini campani e italiani con piccola cucina: taglieri, formaggi, salumi e piatti semplici di qualita. Uno dei wine bar piu amati di Napoli.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["La selezione di vini campani e quella piu completa di Napoli: Taurasi, Fiano, Greco.","I taglieri con i salumi e i formaggi campani sono la scusa perfetta per stare ore.","Il vino bar piu raffinato di Chiaia: frequentato da chi conosce i vini del Sud."]},
  {n:"L'Ebrezza di Teonilla",a:"Via Chiatamone 38, Lungomare",pl:2,pr:"€€ · ~36€",cu:"Enoteca Napoletana",tg:"italiana",ws:"https://www.google.com/search?q=L+Ebrezza+di+Teonilla+Napoli",st:"Enoteca con cucina sul Lungomare di Napoli. Selezione di vini naturali campani e nazionali con cucina leggera: taglieri, formaggi, pasta fresca. Vista sul Castel dell Ovo.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["I vini naturali campani selezionati con passione: una scoperta per ogni visita.","Vista sul Castel dell Ovo e sul Golfo: l aperitivo piu bello del Lungomare.","La cucina leggera con i formaggi campani e i salumi e la scelta giusta con il vino."]},
  {n:"L'Europeo di Mattozzi",a:"Via Marchese Campodisola 4, Toledo",pl:2,pr:"€€ · ~40€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=L'Europeo%20di%20Mattozzi%20ristorante",st:"Trattoria storica napoletana dal 1951 vicino a Toledo. Cucina partenopea autentica: pasta e patate, genovese, ragù napoletano a cottura lenta. Vino sfuso della casa.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Dal 1951 la trattoria napoletana piu autentica del centro: cucina popolare di qualita.","Il ragu napoletano cotto per 6 ore e la pasta e patate sono piatti leggendari.","Vino sfuso della casa e conti bassissimi: un miracolo di qualita e prezzo."]},
  {n:"La Mattonella",a:"Via Giovanni Nicotera 13, Chiaia",pl:2,pr:"€€ · ~38€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=La+Mattonella+Napoli",st:"Osteria napoletana storica a Chiaia con le caratteristiche mattonelle di maioliche. Cucina partenopea autentica: genovese, pasta alla Gennaro, melanzane a parmigiana.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Le mattonelle di maioliche napoletane sono la decorazione piu bella di qualsiasi osteria.","La genovese e la pasta alla Gennaro sono eseguite con la cottura lenta della tradizione.","Chiaia autentica, non turistica: l osteria dei napoletani veri."]},
  {n:"La Notizia",a:"Via Michelangelo da Caravaggio 53, Vomero",pl:2,pr:"€€ · ~22€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.google.com/search?q=La+Notizia+pizzeria+Napoli",st:"Pizzeria di Enzo Coccia al Vomero. Una delle pizzerie piu innovative di Napoli. Impasto a lievitazione naturale, farine selezionate, topping ricercati. Premio internazionale.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Enzo Coccia ha fatto della pizza napoletana un oggetto di studio e di eccellenza.","L impasto a lievitazione naturale con farine selezionate e il piu digeribile di Napoli.","La pizza di La Notizia ha vinto premi internazionali: meritati senza alcun dubbio."]},
  {n:"La Stanza del Gusto",a:"Vico Pisan 17, Spaccanapoli",pl:3,pr:"€€€ · ~65€",cu:"Italiana Creativa",tg:"italiana",ws:"https://www.google.com/search?q=La%20Stanza%20del%20Gusto%20ristorante",st:"Chef Mario Avallone. Ristorante di ricerca nel centro storico di Napoli. Cucina italiana creativa con influenze campane: menu degustazione a sorpresa che racconta il territorio.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Mario Avallone costruisce percorsi degustazione originali con ingredienti campani di eccellenza.","Il menu a sorpresa e una scelta coraggiosa: ci si affida e non si e mai delusi.","Nel cuore del centro storico UNESCO: cucina di ricerca dove non te la aspetti."]},
  {n:"Locanda Gesù Vecchio",a:"Via Gesù Vecchio 8, Spaccanapoli",pl:2,pr:"€€ · ~38€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Locanda+Gesu+Vecchio+Napoli",st:"Locanda nel cuore di Spaccanapoli. Cucina napoletana della tradizione: pasta e fagioli, genovese, zuppa di soffritto. Una delle trattorie piu autentiche del centro storico UNESCO.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["La genovese di Locanda Gesu Vecchio e quella della tradizione: cipolle e manzo cotti per ore.","In Spaccanapoli, la strada piu dritta di Napoli: cucina popolare autentica.","La pasta e fagioli con la cotenna: il comfort food napoletano nella sua forma piu pura."]},
  {n:"Nennella Friggitoria",a:"Vico Lungo Teatro Nuovo 105, Quartieri Spagnoli",pl:1,pr:"€ · ~10€",cu:"Street Food Napoletano",tg:"italiana",ws:"https://www.google.com/search?q=Nennella%20Friggitoria%20ristorante",st:"La friggitoria piu celebre dei Quartieri Spagnoli. Cuoppo di frittura napoletana, pizza fritta, crocche. Lo street food partenopeo nella sua forma piu autentica e popolare.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Il cuoppo di frittura napoletana qui e il meglio che si possa trovare ai Quartieri.","Pizza fritta e crocche di patate: lo street food partenopeo nella sua forma piu pura.","Prezzi da centesimi e qualita altissima: il miracolo della cucina popolare napoletana."]},
  {n:"Osteria della Mattonella",a:"Via Giovanni Nicotera 13, Chiaia",pl:2,pr:"€€ · ~35€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Osteria%20della%20Mattonella%20ristorante",st:"Osteria napoletana storica a Chiaia con le caratteristiche mattonelle di maiolica. Cucina partenopea autentica: genovese, pasta alla Gennaro, melanzane a parmigiana.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:14,l:"14/20"},rv:["Le mattonelle di maiolica napoletana sono la decorazione piu bella di qualsiasi osteria.","La genovese e la pasta alla Gennaro sono eseguite con la cottura lenta della tradizione.","Chiaia autentica, non turistica: l osteria dei napoletani veri."]},
  {n:"Osteria Pignatelli",a:"Via Generale Orsini 18, Chiaia",pl:2,pr:"€€ · ~40€",cu:"Napoletana Contemporanea",tg:"italiana",ws:"https://www.google.com/search?q=Osteria+Pignatelli+Napoli",st:"Osteria contemporanea a Chiaia. Cucina napoletana rivisitata con ingredienti di qualita: frittata di pasta, polpette, spaghetti alle vongole. Vini campani selezionati.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["La frittata di pasta napoletana qui e quella gourmet: pasta avanzata, uova e profumi.","I vini campani selezionati con cura: Fiano di Avellino e Aglianico del Taburno.","Chiaia elegante con una cucina napoletana che non dimentica le radici."]},
  {n:"Palazzo Petrucci",a:"Piazza San Domenico Maggiore 4, Spaccanapoli",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina Napoletana",tg:"italiana",ws:"https://www.google.com/search?q=Palazzo%20Petrucci%20ristorante",st:"Due stelle Michelin in Piazza San Domenico Maggiore. Chef Lino Scarallo. Cucina napoletana d autore nel cuore del centro storico UNESCO. Una delle tavole piu eleganti di Napoli.",mi:{s:2,b:0,g:0},gr:{f:3,l:"Tre Forchette"},es:{v:18,l:"18/20"},rv:["Due stelle Michelin in uno dei palazzi nobiliari piu belli di Napoli.","Lino Scarallo eleva la cucina napoletana a linguaggio d alta cucina internazionale.","La piazza San Domenico Maggiore e il contesto piu bello dove cenare nel centro storico."]},
  {n:"Pizzeria da Michele",a:"Via Cesare Sersale 1, Spaccanapoli",pl:1,pr:"€ · ~8€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.google.com/search?q=Pizzeria%20da%20Michele%20ristorante",st:"Dal 1870 la pizzeria piu famosa del mondo. Solo marinara e margherita. Nient altro. La semplicita elevata a perfezione assoluta: il manifesto della pizza napoletana.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Dal 1870 solo due pizze: la perfezione non ha bisogno di varieta.","La margherita di Da Michele e quella che ha ispirato ogni pizzaiolo al mondo.","Eat Pray Love l ha resa leggendaria: la realta e ancora meglio del film."]},
  {n:"Pizzeria Di Matteo",a:"Via dei Tribunali 94, Spaccanapoli",pl:1,pr:"€ · ~9€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.google.com/search?q=Pizzeria%20Di%20Matteo%20ristorante",st:"Pizzeria storica in Via dei Tribunali dal 1936. Pizza fritta e al forno, cuoppo fritto. Bill Clinton ci e venuto nel 1994 durante il G7 a Napoli: da allora leggenda assoluta.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Bill Clinton ci venne nel 1994 per il G7: da allora la fama e inarrestabile.","La pizza fritta con ricotta e cicoli e quella originale: croccante e fondente.","Via dei Tribunali e la strada delle pizzerie: Di Matteo ne e uno dei pilastri storici."]},
  {n:"Pizzeria Gino Sorbillo",a:"Via dei Tribunali 32, Spaccanapoli",pl:1,pr:"€ · ~12€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.google.com/search?q=Pizzeria%20Gino%20Sorbillo%20ristorante",st:"La pizzeria Sorbillo e un istituzione di Napoli e del mondo. Via dei Tribunali, il cuore della pizza napoletana. Impasto a lievitazione naturale, pomodoro San Marzano DOP, fior di latte.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["La pizza napoletana nella sua forma piu pura e popolare: Sorbillo e un punto di riferimento mondiale.","La fila fuori e sempre lunga ma la pizza vale ogni minuto: cornicione fragrante e condimento perfetto.","Via dei Tribunali e la strada della pizza: Sorbillo ne e il simbolo indiscusso."]},
  {n:"Pizzeria Starita",a:"Via Materdei 27, Quartieri Spagnoli",pl:1,pr:"€ · ~10€",cu:"Pizza Napoletana",tg:"pizza",ws:"https://www.google.com/search?q=Pizzeria%20Starita%20ristorante",st:"Pizzeria storica dal 1901 nel quartiere Materdei. Famosa per aver ospitato le riprese di L Oro di Napoli di Sofia Loren. Pizza fritta e pizza al forno della tradizione napoletana.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Dal 1901 nel quartiere Materdei: una delle pizzerie piu storiche e autentiche di Napoli.","Sofia Loren frigge la pizza qui ne L Oro di Napoli: la storia del cinema incontra la pizza.","La pizza fritta con ricotta e cicoli e la scelta giusta: tradizione napoletana pura."]},
  {n:"Ristorante Caracol",a:"Via Faro 1, Bacoli",pl:5,pr:"€€€€€ · ~130€",cu:"Alta Cucina di Mare",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20Caracol%20ristorante",st:"Una stella Michelin nei Campi Flegrei a Bacoli. Chef Raffaele Cardillo. Cucina di mare tra le banche vulcaniche dei Campi Flegrei. Panorama sul golfo di Pozzuoli. ",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["Tra i crateri vulcanici dei Campi Flegrei: una location impossibile da dimenticare.","Il pesce del Golfo di Pozzuoli e tra i piu freschi e pregiati d Italia.","Una stella Michelin in uno dei posti piu suggestivi della Campania."]},
  {n:"Ristorante La Terrazza dell'Angelo",a:"Via Caracciolo 11, Lungomare",pl:3,pr:"€€€ · ~60€",cu:"Italiana di Pesce",tg:"pesce",ws:"https://www.google.com/search?q=Ristorante%20La%20Terrazza%20dell'Angelo%20ristorante",st:"Ristorante di pesce sul Lungomare con terrazza panoramica sul Golfo di Napoli. Pesce del Golfo freschissimo: crudi, frittura, spaghetti alle vongole. Vista Vesuvio e Castel dell Ovo.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["La terrazza sul Golfo con Vesuvio e Castel dell Ovo: la vista piu iconica di Napoli.","Il pesce del Golfo freschissimo: frittura, crudi e spaghetti alle vongole impeccabili.","La frittura di paranza napoletana qui e tra le piu leggere e croccanti che si possano trovare."]},
  {n:"Ristorante Ristorante dell'Avvocato",a:"Via Santa Lucia 115, Lungomare",pl:4,pr:"€€€€ · ~85€",cu:"Alta Cucina Napoletana",tg:"italiana",ws:"https://www.google.com/search?q=Ristorante%20Ristorante%20dell'Avvocato%20ristorante",st:"Nella guida Michelin. Chef Raffaele Cardillo. Cucina napoletana di ricerca sul Lungomare. Ingredienti del Golfo di Napoli lavorati con tecnica raffinata e rispetto della tradizione.",mi:{s:0,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:15,l:"15/20"},rv:["Chef Cardillo e uno degli interpreti piu interessanti della cucina napoletana contemporanea.","Gli ingredienti del Golfo di Napoli sono selezionati con cura maniacale.","Sul Lungomare con vista sul Castel dell Ovo: la location aggiunge valore a ogni piatto."]},
  {n:"Tandem",a:"Via Giovanni Paladino 51, Centro Storico",pl:1,pr:"€ · ~18€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Tandem+ristorante+Napoli",st:"Il ristorante del ragu napoletano. Un solo piatto: ragu su pasta fresca o pane. Cotto per ore secondo la tradizione partenopea. Uno dei locali piu amati dai napoletani nel centro storico.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["Un solo piatto e basta: il ragu napoletano cotto per ore su fuoco lento.","La pasta con il ragu di Tandem e uno dei piatti piu iconici della Napoli contemporanea.","Prezzi bassissimi per una qualita autentica: sempre pieno, sempre buono."]},
  {n:"Trattoria da Nennella",a:"Vico Lungo Teatro Nuovo 103, Quartieri Spagnoli",pl:1,pr:"€ · ~18€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria%20da%20Nennella%20ristorante",st:"Trattoria storica nei Quartieri Spagnoli. Menu fisso con antipasti, primo, secondo e contorno. Camerieri che cantano e scherzano: l esperienza piu teatrale di Napoli.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["I camerieri cantano e scherzano con i clienti: un pranzo che e sempre uno spettacolo.","Menu fisso a prezzo fisso con cucina napoletana autentica: il miglior affare in citta.","Nei Quartieri Spagnoli: il cuore piu autentico di Napoli, quello che non cambia mai."]},
  {n:"Trattoria Sant'Anna",a:"Via Gennaro Serra 57, Chiaia",pl:2,pr:"€€ · ~36€",cu:"Napoletana Tradizionale",tg:"italiana",ws:"https://www.google.com/search?q=Trattoria+Sant+Anna+Napoli",st:"Trattoria storica a Chiaia. Cucina napoletana popolare di qualita: pasta e patate, polpette al sugo, braciole napoletane. Frequentata dai napoletani come indirizzo fidato di quartiere.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:13,l:"13/20"},rv:["Le braciole napoletane nel sugo sono quelle della nonna: carne arrotolata con pinoli e uvetta.","La pasta e patate con la provola e il piatto piu confortante della cucina partenopea.","Un indirizzo di quartiere vero: frequentato dai napoletani che abitano a Chiaia."]},
  {n:"Veritas",a:"Corso Vittorio Emanuele 141, Chiaia",pl:5,pr:"€€€€€ · ~110€",cu:"Alta Cucina Napoletana",tg:"italiana",ws:"https://www.google.com/search?q=Veritas%20ristorante",st:"Una stella Michelin sul Corso Vittorio Emanuele. Chef Gianluca d Agostino. Cucina napoletana contemporanea: ingredienti di eccellenza campana lavorati con tecnica raffinata.",mi:{s:1,b:0,g:0},gr:{f:2,l:"Due Forchette"},es:{v:16,l:"16/20"},rv:["La cucina napoletana contemporanea qui trova una delle espressioni piu riuscite.","Gli ingredienti campani sono selezionati con ossessione: il terroir nel piatto.","Una stella Michelin per un ristorante che ha fatto crescere la scena napoletana."]},
  {n:"Vinarium",a:"Vico Santa Maria a Cappella Vecchia 7, Chiaia",pl:2,pr:"€€ · ~38€",cu:"Enoteca Napoletana",tg:"italiana",ws:"https://www.google.com/search?q=Vinarium+Napoli",st:"Enoteca con cucina nel cuore di Chiaia. Vini campani e nazionali con cucina napoletana di qualita: crostini con friarielli, taglieri, pasta fresca. Uno dei wine bar piu frequentati.",mi:{s:0,b:0,g:0},gr:{f:1,l:"Una Forchetta"},es:{v:14,l:"14/20"},rv:["La selezione di vini campani e una delle piu ampie di Napoli: Fiano, Greco, Taurasi.","I friarielli saltati con la salsiccia sono il piatto campano piu identitario: qui perfetti.","Chiaia di sera con un buon Taurasi nel bicchiere: l aperitivo napoletano elevato."]}
];
var favs=new Set(JSON.parse(localStorage.getItem('nafav25')||'[]'));
var wish=new Set(JSON.parse(localStorage.getItem('nawish25')||'[]'));
function saveFavs(){localStorage.setItem('nafav25',JSON.stringify(Array.from(favs)));}
function saveWish(){localStorage.setItem('nawish25',JSON.stringify(Array.from(wish)));}

window.toggleWish=function(i){
  var n=R[i].n;
  wish.has(n)?wish.delete(n):wish.add(n);
  saveWish();updateWishCount();render();
};

window.toggleFav=function(i){
  var n=R[i].n;
  favs.has(n)?favs.delete(n):favs.add(n);
  saveFavs();

updateFavCount();render();
};

var S={c:'all',p:'all',g:'all',z:'all',q:'',fav:false,wish:false};

var mainZones=['spaccanapoli','chiaia','lungomare','centro storico','toledo','quartieri spagnoli','posillipo','vomero','sanita','bacoli'];

function getZone(a){return a.split(',').pop().trim().toLowerCase();}

function maps(a){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a+', Milano');}

function miBadge(r){
  if(r.mi.s>=1)return'<span class="sg mi">'+'\u2B50'.repeat(r.mi.s)+' '+(r.mi.s===1?'Una Stella':r.mi.s+' Stelle')+' <span class="gn">Michelin</span></span>';
  if(r.mi.b)return'<span class="sg mi">\uD83D\uDE0A Bib Gourmand <span class="gn">Michelin</span></span>';
  if(r.mi.g)return'<span class="sg mi" style="background:#f0fff4;border-color:#a8d5b5;color:#276749">\uD83C\uDF3F Green Star <span class="gn">Michelin</span></span>';
  return'<span class="sg mi fd">\u2B50 \u2013 <span class="gn">Michelin</span></span>';
}

function makeCard(r,i){
  var isFav=favs.has(r.n);
  var isWish=wish.has(r.n);
  var ta='https://www.tripadvisor.it/Search?q='+encodeURIComponent(r.n+' Napoli');
  var rvs='';
  for(var k=0;k<r.rv.length;k++)rvs+='<div class="rv"><span class="st">\u2605\u2605\u2605\u2605\u2605</span><span>'+r.rv[k]+'</span></div>';
  return '<div class="card">'
    +'<button class="favbtn'+(isFav?' on':'')+'" onclick="toggleFav('+i+')">'+( isFav?'\u2764\uFE0F':'\uD83E\uDD0D')+'</button>'
    +'<button class="wishbtn'+(isWish?' on':'')+'" onclick="toggleWish('+i+')">'+( isWish?'\u2705':'\u2714\uFE0F')+'</button>'
    +'<div class="cb">'
    +'<div class="ctag"><span class="ccu">'+r.cu.toUpperCase()+'</span><span class="cpr">'+r.pr+'</span></div>'
    +'<h2 class="cn"><a href="'+r.ws+'" target="_blank" style="color:inherit;text-decoration:none;">'+r.n+'</a></h2>'
    +'<div class="lks">'
    +'<a href="'+maps(r.a)+'" target="_blank">\uD83D\uDCCD '+r.a+'</a>'
    +'<a href="'+r.ws+'" target="_blank" class="ws">\uD83C\uDF10 Sito web</a>'
    +'<a href="'+ta+'" target="_blank" class="ta">\uD83C\uDF7D TripAdvisor</a>'
    +'</div>'
    +'<div class="sc">'+miBadge(r)
    +'<span class="sg gr">'+'\uD83C\uDF74'.repeat(r.gr.f)+' '+r.gr.l+' <span class="gn">Gambero Rosso</span></span>'
    +'<span class="sg es">\u2615 '+r.es.l+' <span class="gn">L\u2019Espresso</span></span>'
    +'</div>'
    +'<p class="cs">'+r.st+'</p>'
    +'<div class="rvs">'+rvs+'</div>'
    +'</div></div>';
}

function updateFavCount(){
  var n=favs.size;
  document.getElementById('favc').textContent=n>0?'('+n+')':'';
}
function updateWishCount(){
  var n=wish.size;
  document.getElementById('wishc').textContent=n>0?'('+n+')':'';
}

function render(){
  var f=[];
  for(var i=0;i<R.length;i++){
    var r=R[i];
    if(S.c!=='all'&&r.tg!==S.c)continue;
    if(S.p!=='all'&&r.pl!==parseInt(S.p))continue;
    if(S.g==='michelin'&&!r.mi.s&&!r.mi.b&&!r.mi.g)continue;
    if(S.g==='gambero'&&r.gr.f<2)continue;
    if(S.g==='espresso'&&r.es.v<15)continue;
    if(S.z!=='all'){var rz=getZone(r.a);if(S.z==='other'){if(mainZones.indexOf(rz)!==-1)continue;}else{if(rz!==S.z)continue;}}
    if(S.fav&&!favs.has(r.n))continue;
    if(S.wish&&!wish.has(r.n))continue;
    if(S.q){var q=S.q.toLowerCase();var ok=false;var ff=[r.n,r.cu,r.a,r.st];for(var j=0;j<ff.length;j++){if(ff[j].toLowerCase().indexOf(q)>=0){ok=true;break;}}if(!ok)continue;}
    f.push(i);
  }
  document.getElementById('tot').textContent=f.length;
  var rcEl=document.getElementById('rc');if(rcEl)rcEl.textContent=f.length+' risultati';
  var grid=document.getElementById('grid');
  var cards=grid.querySelectorAll('.card');
  for(var k=0;k<cards.length;k++)cards[k].remove();
  document.getElementById('nr').style.display=f.length?'none':'block';
  for(var m=0;m<f.length;m++)grid.insertAdjacentHTML('beforeend',makeCard(R[f[m]],f[m]));
}

document.getElementById('zg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#zg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.z=b.dataset.z;render();});
document.getElementById('cg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#cg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.c=b.dataset.c;render();});
document.getElementById('pg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#pg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.p=b.dataset.p;render();});
document.getElementById('gg').addEventListener('click',function(e){var b=e.target.closest('.fb');if(!b)return;document.querySelectorAll('#gg .fb').forEach(function(x){x.classList.remove('on');});b.classList.add('on');S.g=b.dataset.g;render();});
document.getElementById('favf').addEventListener('click',function(){S.fav=!S.fav;S.wish=false;document.getElementById('wishf').classList.remove('on');this.classList.toggle('on',S.fav);render();});
document.getElementById('wishf').addEventListener('click',function(){S.wish=!S.wish;S.fav=false;document.getElementById('favf').classList.remove('on');this.classList.toggle('on',S.wish);render();});
document.getElementById('srch').addEventListener('input',function(e){S.q=e.target.value;render();});

updateFavCount();
updateWishCount();
render();
